# Generated by Django 4.2.2 on 2023-06-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tarjeta', models.CharField(max_length=16)),
                ('fecha_caducidad', models.DateField()),
                ('cvc', models.CharField(max_length=3)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
