# Generated by Django 4.1.6 on 2023-06-12 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historial_comandes', models.CharField(max_length=30)),
                ('state', models.CharField(choices=[('pending', 'Pendiente'), ('sold', 'Pagado')], default='pending', max_length=20)),
            ],
        ),
    ]
