# Generated by Django 4.1.6 on 2023-06-12 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carreto', '0001_initial'),
        ('comandes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='idCarrito',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carreto.carrito'),
            preserve_default=False,
        ),
    ]
